# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5afd39f6-c7d6-42d4-b32d-266171d60841";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5afd39f6-c7d6-42d4-b32d-266171d60841".device = "/dev/disk/by-uuid/5afd39f6-c7d6-42d4-b32d-266171d60841";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A911-E7C6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c438b7f6-b045-4a09-99e0-528abd93e43a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
